on:
  workflow_dispatch:
    inputs:
      release-as:
        type: string
        description: 'Override the next version of the repository'
        required: false
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
      uses: MapColonies/shared-workflows/.github/workflows/release-please.yaml@add_release_please
      secrets: inherit
      with:
        release-as: ${{ github.event.inputs.release-as }}
