on:
  workflow_dispatch:
    inputs:
      release-as:
        type: string
        description: 'Override the next version of the repository'
        required: false
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event.inputs.release-as != ''
        run: |
          git config user.email "devops@mapcolonies.com"
          git config user.name "mapcolonies[bot]"          
          git commit --allow-empty -m "chore: release ${{ github.event.inputs.release-as  }}" -m "Release-As: ${{ github.event.inputs.release-as  }}"

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
