name: test-update-artifacts-file

on:
  workflow_dispatch:

jobs:
  build-and-push-docker:
      uses: MapColonies/shared-workflows/.github/workflows/update-artifacts-file.yaml@v2
      secrets: inherit
      with:
        scope: infra,3d
        type: helm
        artifact-name: infra-test
        artifact-tag: master
